export const countries = [
  {
    id: '1',
    country: 'Afghanistan',
    flag: 'https://www.worldometers.info/img/flags/af-flag.gif',
    continent: 'Asia',
    capital: 'Kabul',
    population: '42,240,000',
  },
  {
    id: '2',
    country: 'Albania',
    flag: 'https://www.worldometers.info/img/flags/al-flag.gif',
    continent: 'Europe',
    capital: 'Tiranë',
    population: '2,746,000',
  },
  {
    id: '3',
    country: 'Algeria',
    flag: 'https://www.worldometers.info/img/flags/ag-flag.gif',
    continent: 'Africa',
    capital: 'Algiers',
    population: '45,610,000',
  },
  {
    id: '4',
    country: 'Andorra',
    flag: 'https://www.worldometers.info/img/flags/an-flag.gif',
    continent: 'Europe',
    capital: 'Andorra la Vella',
    population: '77,000',
  },
  {
    id: '5',
    country: 'Angola',
    flag: 'https://www.worldometers.info/img/flags/ao-flag.gif',
    continent: 'Africa',
    capital: 'Luanda',
    population: '35,027,000',
  },
  {
    id: '6',
    country: 'Antigua and Barbuda',
    flag: 'https://www.worldometers.info/img/flags/ac-flag.gif',
    continent: 'North America',
    capital: "St. John's",
    population: '99,000',
  },
  {
    id: '7',
    country: 'Argentina',
    flag: 'https://www.worldometers.info/img/flags/ar-flag.gif',
    continent: 'South America',
    capital: 'Buenos Aires',
    population: '45,376,763',
  },
  {
    id: '8',
    country: 'Armenia',
    flag: 'https://www.worldometers.info/img/flags/am-flag.gif',
    continent: 'Asia',
    capital: 'Yerevan',
    population: '2,963,243',
  },
  {
    id: '9',
    country: 'Australia',
    flag: 'https://www.worldometers.info/img/flags/as-flag.gif',
    continent: 'Oceania',
    capital: 'Canberra',
    population: '26,141,369',
  },
  {
    id: '10',
    country: 'Austria',
    flag: 'https://www.worldometers.info/img/flags/au-flag.gif',
    continent: 'Europe',
    capital: 'Vienna',
    population: '8,935,112',
  },
  {
    id: '11',
    country: 'Azerbaijan',
    flag: 'https://www.worldometers.info/img/flags/aj-flag.gif',
    continent: 'Asia',
    capital: 'Baku',
    population: '10,139,177',
  },
  {
    id: '12',
    country: 'Bahamas',
    flag: 'https://www.worldometers.info/img/flags/bf-flag.gif',
    continent: 'North America',
    capital: 'Nassau',
    population: '400,516',
  },
  {
    id: '13',
    country: 'Bahrain',
    flag: 'https://www.worldometers.info/img/flags/ba-flag.gif',
    continent: 'Asia',
    capital: 'Manama',
    population: '1,701,575',
  },
  {
    id: '14',
    country: 'Bangladesh',
    flag: 'https://www.worldometers.info/img/flags/bg-flag.gif',
    continent: 'Asia',
    capital: 'Dhaka',
    population: '171,186,372',
  },
  {
    id: '15',
    country: 'Barbados',
    flag: 'https://www.worldometers.info/img/flags/bb-flag.gif',
    continent: 'North America',
    capital: 'Bridgetown',
    population: '287,371',
  },
  {
    id: '16',
    country: 'Belarus',
    flag: 'https://www.worldometers.info/img/flags/bo-flag.gif',
    continent: 'Europe',
    capital: 'Minsk',
    population: '9,349,645',
  },
  {
    id: '17',
    country: 'Belgium',
    flag: 'https://www.worldometers.info/img/flags/be-flag.gif',
    continent: 'Europe',
    capital: 'Brussels',
    population: '11,720,716',
  },
  {
    id: '18',
    country: 'Belize',
    flag: 'https://www.worldometers.info/img/flags/bh-flag.gif',
    continent: 'North America',
    capital: 'Belmopan',
    population: '441,471',
  },
  {
    id: '19',
    country: 'Benin',
    flag: 'https://www.worldometers.info/img/flags/bn-flag.gif',
    continent: 'Africa',
    capital: 'Porto-Novo',
    population: '13,301,694',
  },
  {
    id: '20',
    country: 'Bhutan',
    flag: 'https://www.worldometers.info/img/flags/bt-flag.gif',
    continent: 'Asia',
    capital: 'Thimphu',
    population: '787,941',
  },
  {
    id: '21',
    country: 'Bolivia',
    flag: 'https://www.worldometers.info/img/flags/bl-flag.gif',
    continent: 'South America',
    capital: 'Sucre',
    population: '12,054,379',
  },
  {
    id: '22',
    country: 'Bosnia and Herzegovina',
    flag: 'https://www.worldometers.info/img/flags/bk-flag.gif',
    continent: 'Europe',
    capital: 'Sarajevo',
    population: '3,280,819',
  },
  {
    id: '23',
    country: 'Botswana',
    flag: 'https://www.worldometers.info/img/flags/bc-flag.gif',
    continent: 'Africa',
    capital: 'Gaborone',
    population: '2,630,296',
  },
  {
    id: '24',
    country: 'Brazil',
    flag: 'https://www.worldometers.info/img/flags/br-flag.gif',
    continent: 'South America',
    capital: 'Brasília',
    population: '213,993,437',
  },

  {
    id: '26',
    country: 'Bulgaria',
    flag: 'https://www.worldometers.info/img/flags/bu-flag.gif',
    continent: 'Europe',
    capital: 'Sofia',
    population: '6,520,314',
  },

  {
    id: '30',
    country: 'Brunei',
    flag: 'https://www.worldometers.info/img/flags/bx-flag.gif',
    continent: 'Asia',
    capital: 'Bandar Seri Begawan',
    population: '445,431',
  },

  {
    id: '32',
    country: 'Burkina Faso',
    flag: 'https://www.worldometers.info/img/flags/uv-flag.gif',
    continent: 'Africa',
    capital: 'Ouagadougou',
    population: '22,100,683',
  },
  {
    id: '33',
    country: 'Burundi',
    flag: 'https://www.worldometers.info/img/flags/by-flag.gif',
    continent: 'Africa',
    capital: 'Gitega',
    population: '12,551,213',
  },
  {
    id: '34',
    country: 'Cabo Verde',
    flag: 'https://www.worldometers.info/img/flags/cv-flag.gif',
    continent: 'Africa',
    capital: 'Praia',
    population: '555,987',
  },
  {
    id: '35',
    country: 'Cambodia',
    flag: 'https://www.worldometers.info/img/flags/cb-flag.gif',
    continent: 'Asia',
    capital: 'Phnom Penh',
    population: '16,718,965',
  },
  {
    id: '36',
    country: 'Cameroon',
    flag: 'https://www.worldometers.info/img/flags/cm-flag.gif',
    continent: 'Africa',
    capital: 'Yaoundé',
    population: '27,198,628',
  },
  {
    id: '37',
    country: 'Canada',
    flag: 'https://www.worldometers.info/img/flags/ca-flag.gif',
    continent: 'North America',
    capital: 'Ottawa',
    population: '38,246,108',
  },
  {
    id: '38',
    country: 'Central African Republic',
    flag: 'https://www.worldometers.info/img/flags/ct-flag.gif',
    continent: 'Africa',
    capital: 'Bangui',
    population: '5,454,533',
  },
  {
    id: '39',
    country: 'Chad',
    flag: 'https://www.worldometers.info/img/flags/cd-flag.gif',
    continent: 'Africa',
    capital: "N'Djamena",
    population: '17,414,108',
  },
  {
    id: '40',
    country: 'Chile',
    flag: 'https://www.worldometers.info/img/flags/ci-flag.gif',
    continent: 'South America',
    capital: 'Santiago',
    population: '19,212,361',
  },
  {
    id: '41',
    country: 'China',
    flag: 'https://www.worldometers.info/img/flags/ch-flag.gif',
    continent: 'Asia',
    capital: 'Beijing',
    population: '1,410,539,758',
  },
  {
    id: '42',
    country: 'Colombia',
    flag: 'https://www.worldometers.info/img/flags/co-flag.gif',
    continent: 'South America',
    capital: 'Bogotá',
    population: '51,512,762',
  },
  {
    id: '43',
    country: 'Comoros',
    flag: 'https://www.worldometers.info/img/flags/cn-flag.gif',
    continent: 'Africa',
    capital: 'Moroni',
    population: '907,419',
  },
  {
    id: '44',
    country: 'Congo, Democratic Republic of the',
    flag: 'https://cdn.britannica.com/94/7194-050-B789AB29/Flag-Democratic-Republic-of-the-Congo.jpg',
    continent: 'Africa',
    capital: 'Kinshasa',
    population: '95,895,000',
  },
  {
    id: '45',
    country: 'Congo, Republic of the',
    flag: 'https://www.worldometers.info/img/flags/cf-flag.gif',
    continent: 'Africa',
    capital: 'Brazzaville',
    population: '5,657,013',
  },
  {
    id: '46',
    country: 'Costa Rica',
    flag: 'https://www.worldometers.info/img/flags/cs-flag.gif',
    continent: 'North America',
    capital: 'San José',
    population: '5,094,114',
  },
  {
    id: '47',
    country: "Côte d'Ivoire",
    flag: 'https://www.worldometers.info/img/flags/iv-flag.gif',
    continent: 'Africa',
    capital: 'Yamoussoukro',
    population: '27,088,000',
  },
  {
    id: '48',
    country: 'Croatia',
    flag: 'https://www.worldometers.info/img/flags/hr-flag.gif',
    continent: 'Europe',
    capital: 'Zagreb',
    population: '3,899,000',
  },
  {
    id: '49',
    country: 'Cuba',
    flag: 'https://www.worldometers.info/img/flags/cu-flag.gif',
    continent: 'North America',
    capital: 'Havana',
    population: '11,113,215',
  },
  {
    id: '50',
    country: 'Cyprus',
    flag: 'https://www.worldometers.info/img/flags/cy-flag.gif',
    continent: 'Asia',
    capital: 'Nicosia',
    population: '1,223,387',
  },
  {
    id: '51',
    country: 'Czech Republic',
    flag: 'https://www.worldometers.info/img/flags/ez-flag.gif',
    continent: 'Europe',
    capital: 'Prague',
    population: '10,693,939',
  },
  {
    id: '52',
    country: 'Denmark',
    flag: 'https://www.worldometers.info/img/flags/da-flag.gif',
    continent: 'Europe',
    capital: 'Copenhagen',
    population: '5,840,045',
  },
  {
    id: '53',
    country: 'Djibouti',
    flag: 'https://www.worldometers.info/img/flags/dj-flag.gif',
    continent: 'Africa',
    capital: 'Djibouti',
    population: '1,074,000',
  },
  {
    id: '54',
    country: 'Dominica',
    flag: 'https://www.worldometers.info/img/flags/do-flag.gif',
    continent: 'North America',
    capital: 'Roseau',
    population: '72,412',
  },
  {
    id: '55',
    country: 'Dominican Republic',
    flag: 'https://www.worldometers.info/img/flags/dr-flag.gif',
    continent: 'North America',
    capital: 'Santo Domingo',
    population: '10,535,535',
  },
  {
    id: '56',
    country: 'Ecuador',
    flag: 'https://www.worldometers.info/img/flags/ec-flag.gif',
    continent: 'South America',
    capital: 'Quito',
    population: '17,797,737',
  },
  {
    id: '57',
    country: 'Egypt',
    flag: 'https://www.worldometers.info/img/flags/eg-flag.gif',
    continent: 'Africa',
    capital: 'Cairo',
    population: '11,117,873',
  },
  {
    id: '58',
    country: 'El Salvador',
    flag: 'https://www.worldometers.info/img/flags/es-flag.gif',
    continent: 'North America',
    capital: 'San Salvador',
    population: '6,521,000',
  },
  {
    id: '59',
    country: 'Equatorial Guinea',
    flag: 'https://www.worldometers.info/img/flags/ek-flag.gif',
    continent: 'Africa',
    capital: 'Malabo',
    population: '1,468,000',
  },
  {
    id: '60',
    country: 'Eritrea',
    flag: 'https://www.worldometers.info/img/flags/er-flag.gif',
    continent: 'Africa',
    capital: 'Asmara',
    population: '3,684,000',
  },
  {
    id: '61',
    country: 'Estonia',
    flag: 'https://www.worldometers.info/img/flags/en-flag.gif',
    continent: 'Europe',
    capital: 'Tallinn',
    population: '1,331,000',
  },
  {
    id: '62',
    country: 'Eswatini',
    flag: 'https://www.worldometers.info/img/flags/wz-flag.gif',
    continent: 'Africa',
    capital: 'Mbabane',
    population: '1,160,000',
  },
  {
    id: '63',
    country: 'Ethiopia',
    flag: 'https://www.worldometers.info/img/flags/et-flag.gif',
    continent: 'Africa',
    capital: 'Addis Ababa',
    population: '126,527,000',
  },
  {
    id: '64',
    country: 'Fiji',
    flag: 'https://www.worldometers.info/img/flags/fj-flag.gif',
    continent: 'Oceania',
    capital: 'Suva',
    population: '926,000',
  },
  {
    id: '65',
    country: 'Finland',
    flag: 'https://www.worldometers.info/img/flags/fi-flag.gif',
    continent: 'Europe',
    capital: 'Helsinki',
    population: '5,540,000',
  },
  {
    id: '66',
    country: 'France',
    flag: 'https://www.worldometers.info/img/flags/fr-flag.gif',
    continent: 'Europe',
    capital: 'Paris',
    population: '64,626,000',
  },
  {
    id: '67',
    country: 'Gabon',
    flag: 'https://www.worldometers.info/img/flags/gb-flag.gif',
    continent: 'Africa',
    capital: 'Libreville',
    population: '2,340,000',
  },
  {
    id: '68',
    country: 'Gambia',
    flag: 'https://www.worldometers.info/img/flags/ga-flag.gif',
    continent: 'Africa',
    capital: 'Banjul',
    population: '2,773,000',
  },
  {
    id: '69',
    country: 'Georgia',
    flag: 'https://www.worldometers.info/img/flags/gg-flag.gif',
    continent: 'Asia',
    capital: 'Tbilisi',
    population: '3,688,000',
  },
  {
    id: '70',
    country: 'Germany',
    flag: 'https://www.worldometers.info/img/flags/gm-flag.gif',
    continent: 'Europe',
    capital: 'Berlin',
    population: '83,191,000',
  },
  {
    id: '71',
    country: 'Ghana',
    flag: 'https://www.worldometers.info/img/flags/gh-flag.gif',
    continent: 'Africa',
    capital: 'Accra',
    population: '33,107,000',
  },
  {
    id: '72',
    country: 'Greece',
    flag: 'https://www.worldometers.info/img/flags/gr-flag.gif',
    continent: 'Europe',
    capital: 'Athens',
    population: '10,432,000',
  },
  {
    id: '73',
    country: 'Grenada',
    flag: 'https://www.worldometers.info/img/flags/gj-flag.gif',
    continent: 'North America',
    capital: "St. George's",
    population: '125,000',
  },
  {
    id: '74',
    country: 'Guatemala',
    flag: 'https://www.worldometers.info/img/flags/gt-flag.gif',
    continent: 'North America',
    capital: 'Guatemala City',
    population: '19,648,000',
  },
  {
    id: '75',
    country: 'Guinea',
    flag: 'https://www.worldometers.info/img/flags/gv-flag.gif',
    continent: 'Africa',
    capital: 'Conakry',
    population: '14,862,000',
  },
  {
    id: '76',
    country: 'Guinea-Bissau',
    flag: 'https://www.worldometers.info/img/flags/pu-flag.gif',
    continent: 'Africa',
    capital: 'Bissau',
    population: '2,060,000',
  },
  {
    id: '77',
    country: 'Guyana',
    flag: 'https://www.worldometers.info/img/flags/gy-flag.gif',
    continent: 'South America',
    capital: 'Georgetown',
    population: '808,000',
  },
  {
    id: '78',
    country: 'Haiti',
    flag: 'https://www.worldometers.info/img/flags/ha-flag.gif',
    continent: 'North America',
    capital: 'Port-au-Prince',
    population: '11,743,000',
  },
  {
    id: '79',
    country: 'Honduras',
    flag: 'https://www.worldometers.info/img/flags/ho-flag.gif',
    continent: 'North America',
    capital: 'Tegucigalpa',
    population: '10,432,000',
  },
  {
    id: '80',
    country: 'Hungary',
    flag: 'https://www.worldometers.info/img/flags/hu-flag.gif',
    continent: 'Europe',
    capital: 'Budapest',
    population: '9,630,000',
  },
  {
    id: '81',
    country: 'Iceland',
    flag: 'https://www.worldometers.info/img/flags/ic-flag.gif',
    continent: 'Europe',
    capital: 'Reykjavík',
    population: '343,599',
  },
  {
    id: '82',
    country: 'India',
    flag: 'https://www.worldometers.info/img/flags/in-flag.gif',
    continent: 'Asia',
    capital: 'New Delhi',
    population: '1,428,627,663',
  },
  {
    id: '83',
    country: 'Indonesia',
    flag: 'https://www.worldometers.info/img/flags/id-flag.gif',
    continent: 'Asia',
    capital: 'Jakarta',
    population: '277,329,163',
  },
  {
    id: '84',
    country: 'Iran',
    flag: 'https://www.worldometers.info/img/flags/ir-flag.gif',
    continent: 'Asia',
    capital: 'Tehran',
    population: '89,172,767',
  },
  {
    id: '85',
    country: 'Iraq',
    flag: 'https://www.worldometers.info/img/flags/iz-flag.gif',
    continent: 'Asia',
    capital: 'Baghdad',
    population: '44,741,000',
  },
  {
    id: '86',
    country: 'Ireland',
    flag: 'https://www.worldometers.info/img/flags/ei-flag.gif',
    continent: 'Europe',
    capital: 'Dublin',
    population: '5,148,000',
  },
  {
    id: '87',
    country: 'Israel',
    flag: 'https://www.worldometers.info/img/flags/is-flag.gif',
    continent: 'Asia',
    capital: 'Jerusalem',
    population: '9,727,000',
  },
  {
    id: '88',
    country: 'Italy',
    flag: 'https://www.worldometers.info/img/flags/it-flag.gif',
    continent: 'Europe',
    capital: 'Rome',
    population: '58,870,762',
  },
  {
    id: '89',
    country: 'Jamaica',
    flag: 'https://www.worldometers.info/img/flags/jm-flag.gif',
    continent: 'North America',
    capital: 'Kingston',
    population: '2,825,000',
  },
  {
    id: '90',
    country: 'Japan',
    flag: 'https://www.worldometers.info/img/flags/ja-flag.gif',
    continent: 'Asia',
    capital: 'Tokyo',
    population: '123,294,513',
  },
  {
    id: '91',
    country: 'Jordan',
    flag: 'https://www.worldometers.info/img/flags/jo-flag.gif',
    continent: 'Asia',
    capital: 'Amman',
    population: '11,042,719',
  },
  {
    id: '92',
    country: 'Kazakhstan',
    flag: 'https://www.worldometers.info/img/flags/kz-flag.gif',
    continent: 'Asia',
    capital: 'Astana',
    population: '19,196,465',
  },
  {
    id: '93',
    country: 'Kenya',
    flag: 'https://www.worldometers.info/img/flags/ke-flag.gif',
    continent: 'Africa',
    capital: 'Nairobi',
    population: '54,027,487',
  },
  {
    id: '94',
    country: 'Kiribati',
    flag: 'https://www.worldometers.info/img/flags/kr-flag.gif',
    continent: 'Oceania',
    capital: 'Tarawa',
    population: '123,419',
  },
  {
    id: '95',
    country: 'Kuwait',
    flag: 'https://www.worldometers.info/img/flags/ku-flag.gif',
    continent: 'Asia',
    capital: 'Kuwait City',
    population: '4,670,000',
  },
  {
    id: '96',
    country: 'Kyrgyzstan',
    flag: 'https://www.worldometers.info/img/flags/kg-flag.gif',
    continent: 'Asia',
    capital: 'Bishkek',
    population: '6,637,000',
  },
  {
    id: '97',
    country: 'Laos',
    flag: 'https://www.worldometers.info/img/flags/la-flag.gif',
    continent: 'Asia',
    capital: 'Vientiane',
    population: '7,749,595',
  },
  {
    id: '98',
    country: 'Latvia',
    flag: 'https://www.worldometers.info/img/flags/lg-flag.gif',
    continent: 'Europe',
    capital: 'Riga',
    population: '1,848,837',
  },
  {
    id: '99',
    country: 'Lebanon',
    flag: 'https://www.worldometers.info/img/flags/le-flag.gif',
    continent: 'Asia',
    capital: 'Beirut',
    population: '5,296,814',
  },
  {
    id: '100',
    country: 'Lesotho',
    flag: 'https://www.worldometers.info/img/flags/lt-flag.gif',
    continent: 'Africa',
    capital: 'Maseru',
    population: '2,281,454',
  },
  {
    id: '101',
    country: 'Liberia',
    flag: 'https://www.worldometers.info/img/flags/li-flag.gif',
    continent: 'Africa',
    capital: 'Monrovia',
    population: '5,193,000',
  },
  {
    id: '102',
    country: 'Libya',
    flag: 'https://www.worldometers.info/img/flags/ly-flag.gif',
    continent: 'Africa',
    capital: 'Tripoli',
    population: '7,017,000',
  },
  {
    id: '103',
    country: 'Liechtenstein',
    flag: 'https://www.worldometers.info/img/flags/ls-flag.gif',
    continent: 'Europe',
    capital: 'Vaduz',
    population: '39,000',
  },
  {
    id: '104',
    country: 'Lithuania',
    flag: 'https://www.worldometers.info/img/flags/lh-flag.gif',
    continent: 'Europe',
    capital: 'Vilnius',
    population: '2,661,000',
  },
  {
    id: '105',
    country: 'Luxembourg',
    flag: 'https://www.worldometers.info/img/flags/lu-flag.gif',
    continent: 'Europe',
    capital: 'Luxembourg',
    population: '645,000',
  },
  {
    id: '106',
    country: 'Madagascar',
    flag: 'https://www.worldometers.info/img/flags/ma-flag.gif',
    continent: 'Africa',
    capital: 'Antananarivo',
    population: '29,178,000',
  },
  {
    id: '107',
    country: 'Malawi',
    flag: 'https://www.worldometers.info/img/flags/mi-flag.gif',
    continent: 'Africa',
    capital: 'Lilongwe',
    population: '21,196,000',
  },
  {
    id: '108',
    country: 'Malaysia',
    flag: 'https://www.worldometers.info/img/flags/my-flag.gif',
    continent: 'Asia',
    capital: 'Kuala Lumpur',
    population: '34,923,000',
  },
  {
    id: '109',
    country: 'Maldives',
    flag: 'https://www.worldometers.info/img/flags/mv-flag.gif',
    continent: 'Asia',
    capital: 'Malé',
    population: '521,000',
  },
  {
    id: '110',
    country: 'Mali',
    flag: 'https://www.worldometers.info/img/flags/ml-flag.gif',
    continent: 'Africa',
    capital: 'Bamako',
    population: '24,429,000',
  },
  {
    id: '111',
    country: 'Malta',
    flag: 'https://www.worldometers.info/img/flags/mt-flag.gif',
    continent: 'Europe',
    capital: 'Valletta',
    population: '514,000',
  },
  {
    id: '112',
    country: 'Marshall Islands',
    flag: 'https://www.worldometers.info/img/flags/rm-flag.gif',
    continent: 'Oceania',
    capital: 'Majuro',
    population: '59,000',
  },
  {
    id: '113',
    country: 'Mauritania',
    flag: 'https://www.worldometers.info/img/flags/mr-flag.gif',
    continent: 'Africa',
    capital: 'Nouakchott',
    population: '5,296,000',
  },
  {
    id: '114',
    country: 'Mauritius',
    flag: 'https://www.worldometers.info/img/flags/mp-flag.gif',
    continent: 'Africa',
    capital: 'Port Louis',
    population: '1,266,000',
  },
  {
    id: '115',
    country: 'Mexico',
    flag: 'https://www.worldometers.info/img/flags/mx-flag.gif',
    continent: 'North America',
    capital: 'Mexico City',
    population: '131,563,000',
  },
  {
    id: '116',
    country: 'Micronesia',
    flag: 'https://www.worldometers.info/img/flags/fm-flag.gif',
    continent: 'Oceania',
    capital: 'Palikir',
    population: '115,000',
  },
  {
    id: '117',
    country: 'Moldova',
    flag: 'https://www.worldometers.info/img/flags/md-flag.gif',
    continent: 'Europe',
    capital: 'Chișinău',
    population: '2,597,000',
  },
  {
    id: '118',
    country: 'Monaco',
    flag: 'https://www.worldometers.info/img/flags/mn-flag.gif',
    continent: 'Europe',
    capital: 'Monaco',
    population: '39,000',
  },
  {
    id: '119',
    country: 'Mongolia',
    flag: 'https://www.worldometers.info/img/flags/mg-flag.gif',
    continent: 'Asia',
    capital: 'Ulaanbaatar',
    population: '3,409,000',
  },
  {
    id: '120',
    country: 'Montenegro',
    flag: 'https://www.worldometers.info/img/flags/mj-flag.gif',
    continent: 'Europe',
    capital: 'Podgorica',
    population: '622,000',
  },
  {
    id: '121',
    country: 'Morocco',
    flag: 'https://www.worldometers.info/img/flags/mo-flag.gif',
    continent: 'Africa',
    capital: 'Rabat',
    population: '37,112,000',
  },
  {
    id: '122',
    country: 'Mozambique',
    flag: 'https://www.worldometers.info/img/flags/mz-flag.gif',
    continent: 'Africa',
    capital: 'Maputo',
    population: '33,089,000',
  },
  {
    id: '123',
    country: 'Myanmar',
    flag: 'https://www.worldometers.info/img/flags/bm-flag.gif',
    continent: 'Asia',
    capital: 'Naypyidaw',
    population: '55,227,000',
  },
  {
    id: '124',
    country: 'Namibia',
    flag: 'https://www.worldometers.info/img/flags/wa-flag.gif',
    continent: 'Africa',
    capital: 'Windhoek',
    population: '2,630,000',
  },
  {
    id: '125',
    country: 'Nauru',
    flag: 'https://www.worldometers.info/img/flags/nr-flag.gif',
    continent: 'Oceania',
    capital: 'Yaren District (de facto)',
    population: '10,000',
  },
  {
    id: '126',
    country: 'Nepal',
    flag: 'https://www.worldometers.info/img/flags/np-flag.gif',
    continent: 'Asia',
    capital: 'Kathmandu',
    population: '30,034,989',
  },
  {
    id: '127',
    country: 'Netherlands',
    flag: 'https://www.worldometers.info/img/flags/nl-flag.gif',
    continent: 'Europe',
    capital: 'Amsterdam',
    population: '17,134,872',
  },
  {
    id: '128',
    country: 'New Zealand',
    flag: 'https://www.worldometers.info/img/flags/nz-flag.gif',
    continent: 'Oceania',
    capital: 'Wellington',
    population: '4,822,233',
  },
  {
    id: '129',
    country: 'Nicaragua',
    flag: 'https://www.worldometers.info/img/flags/nu-flag.gif',
    continent: 'North America',
    capital: 'Managua',
    population: '6,624,554',
  },
  {
    id: '130',
    country: 'Niger',
    flag: 'https://www.worldometers.info/img/flags/ng-flag.gif',
    continent: 'Africa',
    capital: 'Niamey',
    population: '24,206,644',
  },
  {
    id: '131',
    country: 'Nigeria',
    flag: 'https://www.worldometers.info/img/flags/ni-flag.gif',
    continent: 'Africa',
    capital: 'Abuja',
    population: '206,139,589',
  },
  {
    id: '132',
    country: 'North Korea',
    flag: 'https://www.worldometers.info/img/flags/kn-flag.gif',
    continent: 'Asia',
    capital: 'Pyongyang',
    population: '25,778,816',
  },
  {
    id: '133',
    country: 'North Macedonia',
    flag: 'https://www.worldometers.info/img/flags/mk-flag.gif',
    continent: 'Europe',
    capital: 'Skopje',
    population: '2,083,374',
  },
  {
    id: '134',
    country: 'Norway',
    flag: 'https://www.worldometers.info/img/flags/no-flag.gif',
    continent: 'Europe',
    capital: 'Oslo',
    population: '5,421,241',
  },
  {
    id: '135',
    country: 'Oman',
    flag: 'https://www.worldometers.info/img/flags/mu-flag.gif',
    continent: 'Asia',
    capital: 'Muscat',
    population: '5,106,626',
  },
  {
    id: '136',
    country: 'Pakistan',
    flag: 'https://www.worldometers.info/img/flags/pk-flag.gif',
    continent: 'Asia',
    capital: 'Islamabad',
    population: '220,892,340',
  },
  {
    id: '137',
    country: 'Palau',
    flag: 'https://www.worldometers.info/img/flags/ps-flag.gif',
    continent: 'Oceania',
    capital: 'Ngerulmud',
    population: '18,094',
  },
  {
    id: '138',
    country: 'Palestine',
    flag: 'https://www.worldometers.info/img/flags/palestine-flag.gif',
    continent: 'Asia',
    capital: 'East Jerusalem',
    population: '5,101,414',
  },
  {
    id: '139',
    country: 'Panama',
    flag: 'https://www.worldometers.info/img/flags/pm-flag.gif',
    continent: 'North America',
    capital: 'Panama City',
    population: '4,314,767',
  },
  {
    id: '140',
    country: 'Papua New Guinea',
    flag: 'https://www.worldometers.info/img/flags/pp-flag.gif',
    continent: 'Oceania',
    capital: 'Port Moresby',
    population: '8,947,024',
  },
  {
    id: '141',
    country: 'Paraguay',
    flag: 'https://www.worldometers.info/img/flags/pa-flag.gif',
    continent: 'South America',
    capital: 'Asunción',
    population: '7,132,538',
  },
  {
    id: '142',
    country: 'Peru',
    flag: 'https://www.worldometers.info/img/flags/pe-flag.gif',
    continent: 'South America',
    capital: 'Lima',
    population: '32,971,854',
  },
  {
    id: '143',
    country: 'Philippines',
    flag: 'https://www.worldometers.info/img/flags/rp-flag.gif',
    continent: 'Asia',
    capital: 'Manila',
    population: '109,581,078',
  },
  {
    id: '144',
    country: 'Poland',
    flag: 'https://www.worldometers.info/img/flags/pl-flag.gif',
    continent: 'Europe',
    capital: 'Warsaw',
    population: '37,846,611',
  },
  {
    id: '145',
    country: 'Portugal',
    flag: 'https://www.worldometers.info/img/flags/po-flag.gif',
    continent: 'Europe',
    capital: 'Lisbon',
    population: '10,196,709',
  },
  {
    id: '146',
    country: 'Qatar',
    flag: 'https://www.worldometers.info/img/flags/qa-flag.gif',
    continent: 'Asia',
    capital: 'Doha',
    population: '2,881,053',
  },
  {
    id: '147',
    country: 'Romania',
    flag: 'https://www.worldometers.info/img/flags/ro-flag.gif',
    continent: 'Europe',
    capital: 'Bucharest',
    population: '19,237,691',
  },
  {
    id: '148',
    country: 'Russia',
    flag: 'https://www.worldometers.info/img/flags/rs-flag.gif',
    continent: 'Europe',
    capital: 'Moscow',
    population: '145,912,025',
  },
  {
    id: '149',
    country: 'Rwanda',
    flag: 'https://www.worldometers.info/img/flags/rw-flag.gif',
    continent: 'Africa',
    capital: 'Kigali',
    population: '12,374,397',
  },
  {
    id: '150',
    country: 'Saint Kitts and Nevis',
    flag: 'https://www.worldometers.info/img/flags/sc-flag.gif',
    continent: 'North America',
    capital: 'Basseterre',
    population: '53,199',
  },
  {
    id: '151',
    country: 'Saint Lucia',
    flag: 'https://www.worldometers.info/img/flags/st-flag.gif',
    continent: 'North America',
    capital: 'Castries',
    population: '184,999',
  },
  {
    id: '152',
    country: 'Saint Vincent and the Grenadines',
    flag: 'https://www.worldometers.info/img/flags/vc-flag.gif',
    continent: 'North America',
    capital: 'Kingstown',
    population: '110,947',
  },
  {
    id: '153',
    country: 'Samoa',
    flag: 'https://www.worldometers.info/img/flags/ws-flag.gif',
    continent: 'Oceania',
    capital: 'Apia',
    population: '202,506',
  },
  {
    id: '154',
    country: 'San Marino',
    flag: 'https://www.worldometers.info/img/flags/sm-flag.gif',
    continent: 'Europe',
    capital: 'San Marino',
    population: '33,938',
  },
  {
    id: '155',
    country: 'Sao Tome and Principe',
    flag: 'https://www.worldometers.info/img/flags/tp-flag.gif',
    continent: 'Africa',
    capital: 'São Tomé',
    population: '219,159',
  },
  {
    id: '156',
    country: 'Saudi Arabia',
    flag: 'https://www.worldometers.info/img/flags/sa-flag.gif',
    continent: 'Asia',
    capital: 'Riyadh',
    population: '35,340,683',
  },
  {
    id: '157',
    country: 'Senegal',
    flag: 'https://www.worldometers.info/img/flags/sg-flag.gif',
    continent: 'Africa',
    capital: 'Dakar',
    population: '17,196,301',
  },
  {
    id: '158',
    country: 'Serbia',
    flag: 'https://www.worldometers.info/img/flags/ri-flag.gif',
    continent: 'Europe',
    capital: 'Belgrade',
    population: '6,707,000',
  },
  {
    id: '159',
    country: 'Seychelles',
    flag: 'https://www.worldometers.info/img/flags/se-flag.gif',
    continent: 'Africa',
    capital: 'Victoria',
    population: '98,347',
  },
  {
    id: '160',
    country: 'Sierra Leone',
    flag: 'https://www.worldometers.info/img/flags/sl-flag.gif',
    continent: 'Africa',
    capital: 'Freetown',
    population: '8,141,343',
  },
  {
    id: '161',
    country: 'Singapore',
    flag: 'https://www.worldometers.info/img/flags/sn-flag.gif',
    continent: 'Asia',
    capital: 'Singapore',
    population: '5,637,000',
  },
  {
    id: '162',
    country: 'Slovakia',
    flag: 'https://www.worldometers.info/img/flags/lo-flag.gif',
    continent: 'Europe',
    capital: 'Bratislava',
    population: '5,459,000',
  },
  {
    id: '163',
    country: 'Slovenia',
    flag: 'https://www.worldometers.info/img/flags/si-flag.gif',
    continent: 'Europe',
    capital: 'Ljubljana',
    population: '2,108,000',
  },
  {
    id: '164',
    country: 'Solomon Islands',
    flag: 'https://www.worldometers.info/img/flags/bp-flag.gif',
    continent: 'Oceania',
    capital: 'Honiara',
    population: '721,000',
  },
  {
    id: '165',
    country: 'Somalia',
    flag: 'https://www.worldometers.info/img/flags/so-flag.gif',
    continent: 'Africa',
    capital: 'Mogadishu',
    population: '17,066,000',
  },
  {
    id: '166',
    country: 'South Africa',
    flag: 'https://www.worldometers.info/img/flags/sf-flag.gif',
    continent: 'Africa',
    capital: 'Pretoria',
    population: '60,142,000',
  },
  {
    id: '167',
    country: 'South Korea',
    flag: 'https://www.worldometers.info/img/flags/ks-flag.gif',
    continent: 'Asia',
    capital: 'Seoul',
    population: '51,709,000',
  },
  {
    id: '168',
    country: 'South Sudan',
    flag: 'https://www.worldometers.info/img/flags/od-flag.gif',
    continent: 'Africa',
    capital: 'Juba',
    population: '11,193,725',
  },
  {
    id: '169',
    country: 'Spain',
    flag: 'https://www.worldometers.info/img/flags/sp-flag.gif',
    continent: 'Europe',
    capital: 'Madrid',
    population: '47,450,795',
  },
  {
    id: '170',
    country: 'Sri Lanka',
    flag: 'https://www.worldometers.info/img/flags/ce-flag.gif',
    continent: 'Asia',
    capital: 'Sri Jayawardenepura Kotte',
    population: '21,919,000',
  },
  {
    id: '171',
    country: 'Sudan',
    flag: 'https://www.worldometers.info/img/flags/su-flag.gif',
    continent: 'Africa',
    capital: 'Khartoum',
    population: '45,561,556',
  },
  {
    id: '172',
    country: 'Suriname',
    flag: 'https://www.worldometers.info/img/flags/ns-flag.gif',
    continent: 'South America',
    capital: 'Paramaribo',
    population: '618,040',
  },
  {
    id: '173',
    country: 'Sweden',
    flag: 'https://www.worldometers.info/img/flags/sw-flag.gif',
    continent: 'Europe',
    capital: 'Stockholm',
    population: '10,402,070',
  },
  {
    id: '174',
    country: 'Switzerland',
    flag: 'https://www.worldometers.info/img/flags/sz-flag.gif',
    continent: 'Europe',
    capital: 'Bern',
    population: '8,697,000',
  },
  {
    id: '175',
    country: 'Syria',
    flag: 'https://www.worldometers.info/img/flags/sy-flag.gif',
    continent: 'Asia',
    capital: 'Damascus',
    population: '17,500,657',
  },
  {
    id: '176',
    country: 'Tajikistan',
    flag: 'https://www.worldometers.info/img/flags/ti-flag.gif',
    continent: 'Asia',
    capital: 'Dushanbe',
    population: '9,537,645',
  },
  {
    id: '177',
    country: 'Tanzania',
    flag: 'https://www.worldometers.info/img/flags/tz-flag.gif',
    continent: 'Africa',
    capital: 'Dodoma',
    population: '59,734,218',
  },
  {
    id: '178',
    country: 'Thailand',
    flag: 'https://www.worldometers.info/img/flags/th-flag.gif',
    continent: 'Asia',
    capital: 'Bangkok',
    population: '69,799,978',
  },
  {
    id: '179',
    country: 'Timor-Leste',
    flag: 'https://www.worldometers.info/img/flags/tt-flag.gif',
    continent: 'Asia',
    capital: 'Dili',
    population: '1,318,445',
  },
  {
    id: '180',
    country: 'Togo',
    flag: 'https://www.worldometers.info/img/flags/to-flag.gif',
    continent: 'Africa',
    capital: 'Lomé',
    population: '8,278,724',
  },
  {
    id: '181',
    country: 'Tonga',
    flag: 'https://www.worldometers.info/img/flags/tn-flag.gif',
    continent: 'Oceania',
    capital: 'Nukuʻalofa',
    population: '105,695',
  },
  {
    id: '182',
    country: 'Trinidad and Tobago',
    flag: 'https://www.worldometers.info/img/flags/td-flag.gif',
    continent: 'North America',
    capital: 'Port of Spain',
    population: '1,399,488',
  },
  {
    id: '183',
    country: 'Tunisia',
    flag: 'https://www.worldometers.info/img/flags/ts-flag.gif',
    continent: 'Africa',
    capital: 'Tunis',
    population: '11,818,619',
  },
  {
    id: '184',
    country: 'Turkey',
    flag: 'https://www.worldometers.info/img/flags/tu-flag.gif',
    continent: 'Asia',
    capital: 'Ankara',
    population: '84,339,067',
  },
  {
    id: '185',
    country: 'Turkmenistan',
    flag: 'https://www.worldometers.info/img/flags/tx-flag.gif',
    continent: 'Asia',
    capital: 'Ashgabat',
    population: '6,031,200',
  },
  {
    id: '186',
    country: 'Tuvalu',
    flag: 'https://www.worldometers.info/img/flags/tv-flag.gif',
    continent: 'Oceania',
    capital: 'Funafuti',
    population: '11,792',
  },
  {
    id: '187',
    country: 'Uganda',
    flag: 'https://www.worldometers.info/img/flags/ug-flag.gif',
    continent: 'Africa',
    capital: 'Kampala',
    population: '45,741,007',
  },
  {
    id: '188',
    country: 'Ukraine',
    flag: 'https://www.worldometers.info/img/flags/up-flag.gif',
    continent: 'Europe',
    capital: 'Kyiv',
    population: '41,167,336',
  },
  {
    id: '189',
    country: 'United Arab Emirates',
    flag: 'https://www.worldometers.info/img/flags/ae-flag.gif',
    continent: 'Asia',
    capital: 'Abu Dhabi',
    population: '9,890,402',
  },
  {
    id: '190',
    country: 'United Kingdom',
    flag: 'https://www.worldometers.info/img/flags/uk-flag.gif',
    continent: 'Europe',
    capital: 'London',
    population: '67,886,011',
  },
  {
    id: '191',
    country: 'United States',
    flag: 'https://www.worldometers.info/img/flags/us-flag.gif',
    continent: 'North America',
    capital: 'Washington, D.C.',
    population: '331,002,651',
  },
  {
    id: '192',
    country: 'Uruguay',
    flag: 'https://www.worldometers.info/img/flags/uy-flag.gif',
    continent: 'South America',
    capital: 'Montevideo',
    population: '3,473,730',
  },
  {
    id: '193',
    country: 'Uzbekistan',
    flag: 'https://www.worldometers.info/img/flags/uz-flag.gif',
    continent: 'Asia',
    capital: 'Tashkent',
    population: '33,469,203',
  },
  {
    id: '194',
    country: 'Vanuatu',
    flag: 'https://www.worldometers.info/img/flags/nh-flag.gif',
    continent: 'Oceania',
    capital: 'Port Vila',
    population: '307,145',
  },
  {
    id: '195',
    country: 'Vatican City',
    flag: 'https://www.worldometers.info/img/flags/vt-flag.gif',
    continent: 'Europe',
    capital: 'Vatican City',
    population: '801',
  },
]
